In [1]:
import os
import pickle
from pathlib import Path
import numpy as np

# import required module
import sys
 
# append the path of the
# parent directory
sys.path.append("..")
 
# import method from sibling 
# module
from data_utils import save_samples_as_cifs, save_reconstructions_as_cifs, visualize_trajectory
from utils import retrieve_artifacts_by_name


import env

# Load environment variables
env.load_envs()

# Set the cwd to the project root
PROJECT_ROOT: Path = Path(env.get_env("PROJECT_ROOT"))
assert (
    PROJECT_ROOT.exists()
), "You must configure the PROJECT_ROOT environment variable in a .env file!"

os.chdir(PROJECT_ROOT)

cwd = os.getcwd()

c:\Users\dglav\Anaconda3\envs\thesis\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## Parse samples

In [3]:
experiment_name = "sample_known_domains_cdivae_v2"

# artifact_files = retrieve_artifacts_by_name(experiment_name, artifact_type='dataset', project='zeogen', entity='glafk')

# for file in artifact_files:
#     if "samples" in file:
#         with open(file, "rb") as f:
#             samples = pickle.load(f)


samples_file = "samples-sample_known_domains_cdivae_v2.pickle"

with open(f"./samples/{samples_file}", "rb") as f:
    samples = pickle.load(f)
    samples = samples[0]

for sample in samples:
    print(sample.keys())
    print(sample["num_atoms"])
    print(len(sample["frac_coords"]))
    print(sample["frac_coords"].shape)


save_samples_as_cifs(samples, os.path.join(cwd, f"parsed_samples/samples_{experiment_name}"), save_trajectory=True)


dict_keys(['zd', 'zy', 'num_atoms', 'lengths', 'angles', 'frac_coords', 'atom_types', 'domains', 'norm_hoas', 'pred_hoas', 'is_traj', 'all_frac_coords', 'all_atom_types'])
[20 20 20 20 20]
100
(100, 3)
dict_keys(['zd', 'zy', 'num_atoms', 'lengths', 'angles', 'frac_coords', 'atom_types', 'domains', 'norm_hoas', 'pred_hoas', 'is_traj', 'all_frac_coords', 'all_atom_types'])
[36 36 36 36 36]
180
(180, 3)
dict_keys(['zd', 'zy', 'num_atoms', 'lengths', 'angles', 'frac_coords', 'atom_types', 'domains', 'norm_hoas', 'pred_hoas', 'is_traj', 'all_frac_coords', 'all_atom_types'])
[20 20 20 20 20]
100
(100, 3)
dict_keys(['zd', 'zy', 'num_atoms', 'lengths', 'angles', 'frac_coords', 'atom_types', 'domains', 'norm_hoas', 'pred_hoas', 'is_traj', 'all_frac_coords', 'all_atom_types'])
[120 120 120 120 120]
600
(600, 3)
dict_keys(['zd', 'zy', 'num_atoms', 'lengths', 'angles', 'frac_coords', 'atom_types', 'domains', 'norm_hoas', 'pred_hoas', 'is_traj', 'all_frac_coords', 'all_atom_types'])
[24 24 24 24 24

In [ ]:
with open("./samples/samples_low_noise.pickle", "rb") as f:
    samples = pickle.load(f)

print(samples.keys())
print(samples["all_frac_coords"].shape)
samples["atom_types"] = samples["atom_types"].cpu()
samples["angles"] = samples["angles"].cpu()
samples["lengths"] = samples["lengths"].cpu()
samples["num_atoms"] = samples["num_atoms"].cpu()
samples["frac_coords"] = samples["frac_coords"].cpu()
samples["all_frac_coords"] = samples["all_frac_coords"].cpu()

# Split atom types
split_atom_types = np.split(samples["atom_types"], np.cumsum(samples["num_atoms"])[:-1])

# Split fractional coordinates
split_frac_coords = np.split(samples["frac_coords"], np.cumsum(samples["num_atoms"])[:-1])


trajectories = [samples["all_frac_coords"][:, i*48:(i+1)*48] for i in range(50)]

individual_samples = []
for i in range(len(samples["num_atoms"])):
    individual_samples.append({"atom_types": split_atom_types[i], "frac_coords": split_frac_coords[i], "lengths": samples["lengths"][i], "angles": samples["angles"][i]})

print(trajectories[0].shape)
print(trajectories[0].min(), trajectories[0].max())
visualize_trajectory(trajectories[0][-100:,0,:], individual_samples[0]["lengths"])

## Parse reconstructions

In [11]:
experiment_name = "sample_an_reconstruct_after_50_epochs_total_dataset"

# artifact_files = retrieve_artifacts_by_name(experiment_name, artifact_type='dataset', project='zeogen', entity='glafk')

# for file in artifact_files:
#     if "reconstructions" in file:
#         with open(file, "rb") as f:
#             reconstructions = pickle.load(f)

reconstructions_file = "reconstructions-sample_an_reconstruct_after_50_epochs_total_dataset.pickle"

with open(f"./reconstructions/{reconstructions_file}", "rb") as f:
    reconstructions = pickle.load(f)

recon_path = os.path.join(cwd, f"parsed_reconstructions/reconstructions_{experiment_name}")
save_reconstructions_as_cifs(reconstructions, recon_path, save_trajectory=True, downsample_trajectory=True, downsample_frame_rate=5)

Saving to C:\TUE\Thesis\zeogen\parsed_reconstructions/reconstructions_sample_an_reconstruct_after_50_epochs_total_dataset\reconstruction_1.cif.
Saving to C:\TUE\Thesis\zeogen\parsed_reconstructions/reconstructions_sample_an_reconstruct_after_50_epochs_total_dataset\reconstruction_1_traj\step_1.cif.
Saving to C:\TUE\Thesis\zeogen\parsed_reconstructions/reconstructions_sample_an_reconstruct_after_50_epochs_total_dataset\reconstruction_1_traj\step_6.cif.
Saving to C:\TUE\Thesis\zeogen\parsed_reconstructions/reconstructions_sample_an_reconstruct_after_50_epochs_total_dataset\reconstruction_1_traj\step_11.cif.
Saving to C:\TUE\Thesis\zeogen\parsed_reconstructions/reconstructions_sample_an_reconstruct_after_50_epochs_total_dataset\reconstruction_1_traj\step_16.cif.
Saving to C:\TUE\Thesis\zeogen\parsed_reconstructions/reconstructions_sample_an_reconstruct_after_50_epochs_total_dataset\reconstruction_1_traj\step_21.cif.
Saving to C:\TUE\Thesis\zeogen\parsed_reconstructions/reconstructions_sam

KeyboardInterrupt: 

## Parse reconstruction ground truth

In [13]:
experiment_name = "sample_an_reconstruct_after_50_epochs_total_dataset"

# artifact_files = retrieve_artifacts_by_name(experiment_name, artifact_type='dataset', project='zeogen', entity='glafk')

# for file in artifact_files:
#     if "reconstructions" in file and "gt" in file:
#         with open(file, "rb") as f:
#             reconstructions = pickle.load(f)

reconstructions_file_gt = "reconstructions-sample_an_reconstruct_after_50_epochs_total_dataset_gt.pickle"

with open(f"./reconstructions/{reconstructions_file_gt}", "rb") as f:
    reconstructions_gt = pickle.load(f)

recon_path = os.path.join(cwd, f"parsed_reconstructions/reconstructions_{experiment_name}_gt")
save_reconstructions_as_cifs(reconstructions_gt, recon_path, ground_truth=True)

Saving to C:\TUE\Thesis\zeogen\parsed_reconstructions/reconstructions_sample_an_reconstruct_after_50_epochs_total_dataset_gt\reconstruction_1_gt.cif.
Saving to C:\TUE\Thesis\zeogen\parsed_reconstructions/reconstructions_sample_an_reconstruct_after_50_epochs_total_dataset_gt\reconstruction_2_gt.cif.
Saving to C:\TUE\Thesis\zeogen\parsed_reconstructions/reconstructions_sample_an_reconstruct_after_50_epochs_total_dataset_gt\reconstruction_3_gt.cif.
Saving to C:\TUE\Thesis\zeogen\parsed_reconstructions/reconstructions_sample_an_reconstruct_after_50_epochs_total_dataset_gt\reconstruction_4_gt.cif.
Saving to C:\TUE\Thesis\zeogen\parsed_reconstructions/reconstructions_sample_an_reconstruct_after_50_epochs_total_dataset_gt\reconstruction_5_gt.cif.
Saving to C:\TUE\Thesis\zeogen\parsed_reconstructions/reconstructions_sample_an_reconstruct_after_50_epochs_total_dataset_gt\reconstruction_6_gt.cif.
Saving to C:\TUE\Thesis\zeogen\parsed_reconstructions/reconstructions_sample_an_reconstruct_after_50